### ISSUE TITLE
(Auth) Layout settings

### ISSUE THREAD

**Issue by rhkdgns95** [rhkdgns95/kairos#5]
**Todo**
- [x] Layout part 1 - Navbar
- [x] Layout part 2 - Content
- [x] Update Actions - label.yml

@rhkdgns95
