### ISSUE TITLE
Page - FeedContent

### ISSUE THREAD

**Issue by rhkdgns95** [rhkdgns95/kairos#6]
**Todo**
- [x] Create Auth Router
- [x] Top Menu - 'Keyword', 'SearchBar', 'Buttons'
- [x] Board Card
- [x] Board Card - Details Modal

@rhkdgns95
